# Action Dec definition

# 

# Action Goal

# x1 -- number 1
int64 x1 
# x2 -- number 2
float64 x2 

---

# Action Result

# y -- the result
float64 y 

---

# Action Feedback

# h -- 
std_msgs/Header h 
# yt -- The current result
float64 yt 
