# Service SrFloatFloatString definition

# Service for testing purposes

# Service Request

# x -- x value for float service SrFloatFloatString request 1
float64 x

# y -- y value for float service SrFloatFloatString request 2
float32 y


---

# Service Response

# z -- z value for string service SrFloatFloatString response
string z

