# Service Addtwo definition

# Service for receiving two numbers and returning their their sum

# Service Request

# a -- a value for integer service Addtwo request 1
int64 a = 5
# b -- b value for integer service Addtwo request 2
int64 b

---

# Service Response

# c -- c value for integer service Addtwo response
int32 c
