# Service SrFloatFloatString definition

# Service for testing purposes


# x -- x value for float service SrFloatFloatString request 1
float32 x


# y -- y value for float service SrFloatFloatString request 2
float32 y



---

# z -- z value for string service SrFloatFloatString response
string z


