# Action Increase definition

# Action for enabling counters

# Action Goal

# start -- a value for start value
int64 start

# goal -- a value for goal value
int64 goal


---

# Action Result

# a -- a value for result trigger
int64 a


---

# Action Feedback

# update -- a value for feedback
int64 update

