<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel" nsURI="http://www.example.org/metamodel" nsPrefix="metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="Client">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="servicePath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicemessage" lowerBound="1"
        eType="#//ServiceMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSubscribers" upperBound="-1"
        eType="#//Subscriber" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPublishers" upperBound="-1"
        eType="#//Publisher" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasClients" upperBound="-1"
        eType="#//Client" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasServers" upperBound="-1"
        eType="#//Server" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasParameters" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasActionServers" upperBound="-1"
        eType="#//ActionServer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasActionClients" upperBound="-1"
        eType="#//ActionClient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subscriber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topicPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="smsg" lowerBound="1" eType="#//TopicMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Publisher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topicPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publishRate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pmsg" lowerBound="1" eType="#//TopicMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Server">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="servicePath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicemessage" lowerBound="1"
        eType="#//ServiceMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DataTypes"
        defaultValueLiteral="DataTypes.float32"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasDependencies" upperBound="-1"
        eType="#//Dependency" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasNodes" upperBound="-1"
        eType="#//Node" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasDocumentation" lowerBound="1"
        eType="#//Documentation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rosVersion" lowerBound="1"
        upperBound="-1" eType="#//ROSVersion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packagePath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRosMessages" upperBound="-1"
        eType="#//RosMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRosServices" upperBound="-1"
        eType="#//RosService" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency"/>
  <eClassifiers xsi:type="ecore:EClass" name="Documentation"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DataTypes">
    <eLiterals name="int32" value="2"/>
    <eLiterals name="int8"/>
    <eLiterals name="int16" value="1"/>
    <eLiterals name="int64" value="3"/>
    <eLiterals name="uint8" value="4"/>
    <eLiterals name="uint32" value="6"/>
    <eLiterals name="uint16" value="5"/>
    <eLiterals name="uint64" value="7"/>
    <eLiterals name="float32" value="8"/>
    <eLiterals name="float64" value="9"/>
    <eLiterals name="string" value="10"/>
    <eLiterals name="bool" value="11"/>
    <eLiterals name="enumeration" value="12"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasTopics" upperBound="-1"
        eType="#//Topic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasServiceLinks" upperBound="-1"
        eType="#//ServiceLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topic">
    <eStructuralFeatures xsi:type="ecore:EReference" name="publisher" lowerBound="1"
        eType="#//Publisher"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscriber" upperBound="-1"
        eType="#//Subscriber"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topicPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="server" lowerBound="1"
        eType="#//Server"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//Client"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomService" eSuperTypes="#//ServiceMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRequest" lowerBound="1"
        eType="#//Request" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasResponse" lowerBound="1"
        eType="#//Response" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasObjectProperties" upperBound="-1"
        eType="#//ObjectProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Response">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasObjectProperties" upperBound="-1"
        eType="#//ObjectProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomMessage" eSuperTypes="#//TopicMessage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasObjectProperties" upperBound="-1"
        eType="#//ObjectProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topology" lowerBound="1"
        eType="#//Topology" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPackages" upperBound="-1"
        eType="#//Package" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasGraphs" lowerBound="1"
        eType="#//Graph" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasCustomMessages" upperBound="-1"
        eType="#//CustomMessage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasCustomServices" upperBound="-1"
        eType="#//CustomService" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasCustomActionInterfaces"
        upperBound="-1" eType="#//CustomActionInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Topology">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasPlatforms" upperBound="-1"
        eType="#//Platform" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="network" eType="#//LocalNetwork"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Platform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasHost" upperBound="-1"
        eType="#//Host" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalNetwork">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subnetMask" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gateway" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Host">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="architecture" lowerBound="1"
        eType="#//AritectureTypes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OS" lowerBound="1" eType="#//OSType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hardDisk" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memory" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rosVersion" lowerBound="1"
        eType="#//ROSVersion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasNetworkInterfaces" upperBound="-1"
        eType="#//NetworkInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionServer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actioninterface" lowerBound="1"
        eType="#//ActionInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionClient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actioninterface" lowerBound="1"
        eType="#//ActionInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ROSVersion">
    <eLiterals name="Eloquent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AritectureTypes">
    <eLiterals name="x86"/>
    <eLiterals name="x64" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OSType">
    <eLiterals name="Ubuntu_14"/>
    <eLiterals name="Ubuntu_16" value="1"/>
    <eLiterals name="Ubuntu_18" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gateway" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subnetMask" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datatype" lowerBound="1"
        eType="#//Datatype" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datatype" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Bool" eSuperTypes="#//Datatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;bool&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="String" eSuperTypes="#//Datatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="&quot;string&quot;"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Number" abstract="true" eSuperTypes="#//Datatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="Int" eSuperTypes="#//Number">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//IntType"
        defaultValueLiteral="IntType.int32"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Uint" eSuperTypes="#//Number">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//UIntType"
        defaultValueLiteral="UIntType.uint32"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Float" eSuperTypes="#//Number">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//FloatType"
        defaultValueLiteral="FloatType.float32"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UIntType">
    <eLiterals name="uint8"/>
    <eLiterals name="uint16" value="1"/>
    <eLiterals name="uint32" value="2"/>
    <eLiterals name="uint64" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntType">
    <eLiterals name="int8"/>
    <eLiterals name="int16" value="1"/>
    <eLiterals name="int32" value="2"/>
    <eLiterals name="int64" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FloatType">
    <eLiterals name="float32"/>
    <eLiterals name="float64" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ROSData" eSuperTypes="#//Datatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Array" abstract="true" eSuperTypes="#//Datatype"/>
  <eClassifiers xsi:type="ecore:EClass" name="UintArray" eSuperTypes="#//Array">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//UIntArrayType"
        defaultValueLiteral="UIntArrayType.uint32"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatArray" eSuperTypes="#//Array">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//FloatArrayType"
        defaultValueLiteral="FloatArrayType.float32"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntArray" eSuperTypes="#//Array">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//IntArrayType"
        defaultValueLiteral="IntArrayType.int32"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntArrayType">
    <eLiterals name="int8[]"/>
    <eLiterals name="int16[]" value="1"/>
    <eLiterals name="int32[]" value="2"/>
    <eLiterals name="int64[]" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UIntArrayType">
    <eLiterals name="uint8[]"/>
    <eLiterals name="uint16[]" value="1"/>
    <eLiterals name="uint32[]" value="2"/>
    <eLiterals name="uint64[]" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FloatArrayType">
    <eLiterals name="float32[]"/>
    <eLiterals name="float64[]" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//Datatype">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasElements" lowerBound="1"
        upperBound="-1" eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicMessage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosMessage" eSuperTypes="#//TopicMessage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceMessage" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosService" eSuperTypes="#//ServiceMessage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionInterface" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomActionInterface" eSuperTypes="#//ActionInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasGoal" lowerBound="1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasResult" lowerBound="1"
        eType="#//Result" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasFeedback" lowerBound="1"
        eType="#//Feedback" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasObjectProperties" upperBound="-1"
        eType="#//ObjectProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Result">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasObjectProperties" upperBound="-1"
        eType="#//ObjectProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feedback">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasObjectProperties" upperBound="-1"
        eType="#//ObjectProperty" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
